### ISSUE TITLE
Support for specifying timestamp rather than calculating it

### ISSUE THREAD

**Issue by tomkerkhove** [PrometheusClientNet/Prometheus.Client#21]
Support for specifying timestamp rather than calculating it would be great because sometimes there is a gap between measuring and tracking it where it should use the measuring stamp.

**Comment by sanych-sun** [comment]
@tomkerkhove could you please provide more information on your use case? Is it custom collector on your side? or do you need to import some historical records? 

If you provide the information we will try to include needed changes into upcoming v3 release.

Thanks

**Comment by phnx47** [comment]
@sanych-sun I used 'bool' includeTimestamp. I think, we should  accept 'bool' and 'timestamp'.

Previous issue: https://github.com/PrometheusClientNet/Prometheus.Client/issues/18

**Comment by tomkerkhove** [comment]
That's correct - Would like to specify my own Datetime Offset.

Tom Kerkhove
Azure Architect at Codit, Microsoft Azure MVP

________________________________

**Comment by sanych-sun** [comment]
Ok.
I can see 2 options here, depends on your use-case:

1) you have some external metrics which you currently integrate in the library as IOnDemandCollector. I would like to let you know that in upcoming v3 we will remove IOnDemandCollector by ICollector. And we introduce IMetricWriter which helps to collect your custom data (like that, please note that work in progress and some details could be changed and more examples will be provided): [https://github.com/PrometheusClientNet/Prometheus.Client/blob/master/src/Prometheus.Client/Collectors/ProcessStats/ProcessCollector.cs].

2) if you want to use build-in metrics, but specify timestamps on observation. In this case we have to add new parameter/overload to the metrics collection methods to accept observation date. Like that:
`Inc(double increment, DateTime timestamp = DateTime.UtcNow);`

Second option require more changes to be done. Let's discuss the best way to cover your use-case.
Thanks.

**Comment by tomkerkhove** [comment]
I would prefer option 2 as I'm not using any collectors or so.

**Comment by sanych-sun** [comment]
Thank you for the response. So here is complete proposal:

1) New overload should be added to all value observation methods to accept observation timestamp as a time in unix format (number of milliseconds since epoch start) and extension methods for convenient usage accepting timestamp as DateTime or DateTimeOffset.

2) Provided timestamps will be ignored if metrics was created with IncludeTimestamp parameter set to false.

3) If user code make an observation without providing explicit timestamp - UtcNow is used

4) Library will use explicit timestamp if it's not less then current value of timestamp for the metric:
```
counter.Inc({2 minutes ago}); // timestamp set to {2 minutes ago}
counter.Inc(); // timestamp set to UtcNow 
counter.Inc({2 minutes ago}) // the value will be ignore, because current timestamp is bigger
```

5) Observation method should ignore (or throw) on timestamps that is differ from the current time by more than 5 minutes ( https://stackoverflow.com/questions/43890629/prometheus-timestamps ) Have to find out some information on the Prometheus official site.

**Comment by sanych-sun** [comment]
@tomkerkhove could you please confirm if proposal above covers your use-case?

**Comment by tomkerkhove** [comment]
Sorry for not replying @sanych-sun 	, missed this notification during travel!

This is fine for me, option 1 is what I will be using - Thanks!

**Comment by sanych-sun** [comment]
@tomkerkhove Good news 😊, the changes are done and merged in master. So new extra parameter will be available next release (but we still have some extra tasks to be done, before we cut the release).
